package com.boz.bean;

public class Cixing {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_lib_cixing.id
     *
     * @mbg.generated Fri Mar 08 13:29:48 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_lib_cixing.zi
     *
     * @mbg.generated Fri Mar 08 13:29:48 CST 2019
     */
    private String zi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_lib_cixing.zi_pinyin
     *
     * @mbg.generated Fri Mar 08 13:29:48 CST 2019
     */
    private String ziPinyin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_lib_cixing.zi_py
     *
     * @mbg.generated Fri Mar 08 13:29:48 CST 2019
     */
    private String ziPy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_lib_cixing.py
     *
     * @mbg.generated Fri Mar 08 13:29:48 CST 2019
     */
    private String py;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_lib_cixing.cizu
     *
     * @mbg.generated Fri Mar 08 13:29:48 CST 2019
     */
    private String cizu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_lib_cixing.id
     *
     * @return the value of yw_lib_cixing.id
     *
     * @mbg.generated Fri Mar 08 13:29:48 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_lib_cixing.id
     *
     * @param id the value for yw_lib_cixing.id
     *
     * @mbg.generated Fri Mar 08 13:29:48 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_lib_cixing.zi
     *
     * @return the value of yw_lib_cixing.zi
     *
     * @mbg.generated Fri Mar 08 13:29:48 CST 2019
     */
    public String getZi() {
        return zi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_lib_cixing.zi
     *
     * @param zi the value for yw_lib_cixing.zi
     *
     * @mbg.generated Fri Mar 08 13:29:48 CST 2019
     */
    public void setZi(String zi) {
        this.zi = zi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_lib_cixing.zi_pinyin
     *
     * @return the value of yw_lib_cixing.zi_pinyin
     *
     * @mbg.generated Fri Mar 08 13:29:48 CST 2019
     */
    public String getZiPinyin() {
        return ziPinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_lib_cixing.zi_pinyin
     *
     * @param ziPinyin the value for yw_lib_cixing.zi_pinyin
     *
     * @mbg.generated Fri Mar 08 13:29:48 CST 2019
     */
    public void setZiPinyin(String ziPinyin) {
        this.ziPinyin = ziPinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_lib_cixing.zi_py
     *
     * @return the value of yw_lib_cixing.zi_py
     *
     * @mbg.generated Fri Mar 08 13:29:48 CST 2019
     */
    public String getZiPy() {
        return ziPy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_lib_cixing.zi_py
     *
     * @param ziPy the value for yw_lib_cixing.zi_py
     *
     * @mbg.generated Fri Mar 08 13:29:48 CST 2019
     */
    public void setZiPy(String ziPy) {
        this.ziPy = ziPy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_lib_cixing.py
     *
     * @return the value of yw_lib_cixing.py
     *
     * @mbg.generated Fri Mar 08 13:29:48 CST 2019
     */
    public String getPy() {
        return py;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_lib_cixing.py
     *
     * @param py the value for yw_lib_cixing.py
     *
     * @mbg.generated Fri Mar 08 13:29:48 CST 2019
     */
    public void setPy(String py) {
        this.py = py;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_lib_cixing.cizu
     *
     * @return the value of yw_lib_cixing.cizu
     *
     * @mbg.generated Fri Mar 08 13:29:48 CST 2019
     */
    public String getCizu() {
        return cizu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_lib_cixing.cizu
     *
     * @param cizu the value for yw_lib_cixing.cizu
     *
     * @mbg.generated Fri Mar 08 13:29:48 CST 2019
     */
    public void setCizu(String cizu) {
        this.cizu = cizu;
    }
}