package com.boz.bean;

public class MusicGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_music_group.id
     *
     * @mbg.generated Wed Jan 23 12:52:54 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_music_group.title
     *
     * @mbg.generated Wed Jan 23 12:52:54 CST 2019
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_music_group.id
     *
     * @return the value of art_music_group.id
     *
     * @mbg.generated Wed Jan 23 12:52:54 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_music_group.id
     *
     * @param id the value for art_music_group.id
     *
     * @mbg.generated Wed Jan 23 12:52:54 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_music_group.title
     *
     * @return the value of art_music_group.title
     *
     * @mbg.generated Wed Jan 23 12:52:54 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_music_group.title
     *
     * @param title the value for art_music_group.title
     *
     * @mbg.generated Wed Jan 23 12:52:54 CST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }
}