package com.boz.bean;

public class MusicInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_music_info.id
     *
     * @mbg.generated Wed Jan 23 12:52:39 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_music_info.groupid
     *
     * @mbg.generated Wed Jan 23 12:52:39 CST 2019
     */
    private Integer groupid;

    private MusicGroup musicGroup;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_music_info.music_name
     *
     * @mbg.generated Wed Jan 23 12:52:39 CST 2019
     */
    private String musicName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_music_info.music_filename
     *
     * @mbg.generated Wed Jan 23 12:52:39 CST 2019
     */
    private String musicFilename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_music_info.music_filepath
     *
     * @mbg.generated Wed Jan 23 12:52:39 CST 2019
     */
    private String musicFilepath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_music_info.id
     *
     * @return the value of art_music_info.id
     *
     * @mbg.generated Wed Jan 23 12:52:39 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_music_info.id
     *
     * @param id the value for art_music_info.id
     *
     * @mbg.generated Wed Jan 23 12:52:39 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_music_info.groupid
     *
     * @return the value of art_music_info.groupid
     *
     * @mbg.generated Wed Jan 23 12:52:39 CST 2019
     */
    public Integer getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_music_info.groupid
     *
     * @param groupid the value for art_music_info.groupid
     *
     * @mbg.generated Wed Jan 23 12:52:39 CST 2019
     */
    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_music_info.music_name
     *
     * @return the value of art_music_info.music_name
     *
     * @mbg.generated Wed Jan 23 12:52:39 CST 2019
     */
    public String getMusicName() {
        return musicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_music_info.music_name
     *
     * @param musicName the value for art_music_info.music_name
     *
     * @mbg.generated Wed Jan 23 12:52:39 CST 2019
     */
    public void setMusicName(String musicName) {
        this.musicName = musicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_music_info.music_filename
     *
     * @return the value of art_music_info.music_filename
     *
     * @mbg.generated Wed Jan 23 12:52:39 CST 2019
     */
    public String getMusicFilename() {
        return musicFilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_music_info.music_filename
     *
     * @param musicFilename the value for art_music_info.music_filename
     *
     * @mbg.generated Wed Jan 23 12:52:39 CST 2019
     */
    public void setMusicFilename(String musicFilename) {
        this.musicFilename = musicFilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_music_info.music_filepath
     *
     * @return the value of art_music_info.music_filepath
     *
     * @mbg.generated Wed Jan 23 12:52:39 CST 2019
     */
    public String getMusicFilepath() {
        return musicFilepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_music_info.music_filepath
     *
     * @param musicFilepath the value for art_music_info.music_filepath
     *
     * @mbg.generated Wed Jan 23 12:52:39 CST 2019
     */
    public void setMusicFilepath(String musicFilepath) {
        this.musicFilepath = musicFilepath;
    }

    public MusicGroup getMusicGroup() {
        return musicGroup;
    }

    public void setMusicGroup(MusicGroup musicGroup) {
        this.musicGroup = musicGroup;
    }
}