package com.boz.bean;

public class UserAdmin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_user_admin.uid
     *
     * @mbg.generated Tue Jan 22 11:25:52 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_user_admin.username
     *
     * @mbg.generated Tue Jan 22 11:25:52 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_user_admin.truename
     *
     * @mbg.generated Tue Jan 22 11:25:52 CST 2019
     */
    private String truename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_user_admin.pwd
     *
     * @mbg.generated Tue Jan 22 11:25:52 CST 2019
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_user_admin.ifadmin
     *
     * @mbg.generated Tue Jan 22 11:25:52 CST 2019
     */
    private Integer ifadmin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_user_admin.uid
     *
     * @return the value of art_user_admin.uid
     *
     * @mbg.generated Tue Jan 22 11:25:52 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_user_admin.uid
     *
     * @param uid the value for art_user_admin.uid
     *
     * @mbg.generated Tue Jan 22 11:25:52 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_user_admin.username
     *
     * @return the value of art_user_admin.username
     *
     * @mbg.generated Tue Jan 22 11:25:52 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_user_admin.username
     *
     * @param username the value for art_user_admin.username
     *
     * @mbg.generated Tue Jan 22 11:25:52 CST 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_user_admin.truename
     *
     * @return the value of art_user_admin.truename
     *
     * @mbg.generated Tue Jan 22 11:25:52 CST 2019
     */
    public String getTruename() {
        return truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_user_admin.truename
     *
     * @param truename the value for art_user_admin.truename
     *
     * @mbg.generated Tue Jan 22 11:25:52 CST 2019
     */
    public void setTruename(String truename) {
        this.truename = truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_user_admin.pwd
     *
     * @return the value of art_user_admin.pwd
     *
     * @mbg.generated Tue Jan 22 11:25:52 CST 2019
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_user_admin.pwd
     *
     * @param pwd the value for art_user_admin.pwd
     *
     * @mbg.generated Tue Jan 22 11:25:52 CST 2019
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_user_admin.ifadmin
     *
     * @return the value of art_user_admin.ifadmin
     *
     * @mbg.generated Tue Jan 22 11:25:52 CST 2019
     */
    public Integer getIfadmin() {
        return ifadmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_user_admin.ifadmin
     *
     * @param ifadmin the value for art_user_admin.ifadmin
     *
     * @mbg.generated Tue Jan 22 11:25:52 CST 2019
     */
    public void setIfadmin(Integer ifadmin) {
        this.ifadmin = ifadmin;
    }
}