package com.boz.bean;

public class Zi {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_lib_zi.id
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_lib_zi.zi
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    private String zi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_lib_zi.fzi
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    private String fzi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_lib_zi.py
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    private String py;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_lib_zi.zipin
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    private Integer zipin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_lib_zi.pinyin
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    private String pinyin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_lib_zi.wubi
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    private String wubi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_lib_zi.bushou
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    private String bushou;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_lib_zi.jiegou
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    private Integer jiegou;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_lib_zi.zongbihua
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    private Integer zongbihua;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_lib_zi.buwaibihua
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    private Integer buwaibihua;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_lib_zi.pys
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    private String pys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_lib_zi.bishun
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    private String bishun;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_lib_zi.bushoupic
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    private String bushoupic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_lib_zi.id
     *
     * @return the value of yw_lib_zi.id
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_lib_zi.id
     *
     * @param id the value for yw_lib_zi.id
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_lib_zi.zi
     *
     * @return the value of yw_lib_zi.zi
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    public String getZi() {
        return zi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_lib_zi.zi
     *
     * @param zi the value for yw_lib_zi.zi
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    public void setZi(String zi) {
        this.zi = zi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_lib_zi.fzi
     *
     * @return the value of yw_lib_zi.fzi
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    public String getFzi() {
        return fzi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_lib_zi.fzi
     *
     * @param fzi the value for yw_lib_zi.fzi
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    public void setFzi(String fzi) {
        this.fzi = fzi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_lib_zi.py
     *
     * @return the value of yw_lib_zi.py
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    public String getPy() {
        return py;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_lib_zi.py
     *
     * @param py the value for yw_lib_zi.py
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    public void setPy(String py) {
        this.py = py;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_lib_zi.zipin
     *
     * @return the value of yw_lib_zi.zipin
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    public Integer getZipin() {
        return zipin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_lib_zi.zipin
     *
     * @param zipin the value for yw_lib_zi.zipin
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    public void setZipin(Integer zipin) {
        this.zipin = zipin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_lib_zi.pinyin
     *
     * @return the value of yw_lib_zi.pinyin
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_lib_zi.pinyin
     *
     * @param pinyin the value for yw_lib_zi.pinyin
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_lib_zi.wubi
     *
     * @return the value of yw_lib_zi.wubi
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    public String getWubi() {
        return wubi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_lib_zi.wubi
     *
     * @param wubi the value for yw_lib_zi.wubi
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    public void setWubi(String wubi) {
        this.wubi = wubi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_lib_zi.bushou
     *
     * @return the value of yw_lib_zi.bushou
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    public String getBushou() {
        return bushou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_lib_zi.bushou
     *
     * @param bushou the value for yw_lib_zi.bushou
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    public void setBushou(String bushou) {
        this.bushou = bushou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_lib_zi.jiegou
     *
     * @return the value of yw_lib_zi.jiegou
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    public Integer getJiegou() {
        return jiegou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_lib_zi.jiegou
     *
     * @param jiegou the value for yw_lib_zi.jiegou
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    public void setJiegou(Integer jiegou) {
        this.jiegou = jiegou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_lib_zi.zongbihua
     *
     * @return the value of yw_lib_zi.zongbihua
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    public Integer getZongbihua() {
        return zongbihua;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_lib_zi.zongbihua
     *
     * @param zongbihua the value for yw_lib_zi.zongbihua
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    public void setZongbihua(Integer zongbihua) {
        this.zongbihua = zongbihua;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_lib_zi.buwaibihua
     *
     * @return the value of yw_lib_zi.buwaibihua
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    public Integer getBuwaibihua() {
        return buwaibihua;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_lib_zi.buwaibihua
     *
     * @param buwaibihua the value for yw_lib_zi.buwaibihua
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    public void setBuwaibihua(Integer buwaibihua) {
        this.buwaibihua = buwaibihua;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_lib_zi.pys
     *
     * @return the value of yw_lib_zi.pys
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    public String getPys() {
        return pys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_lib_zi.pys
     *
     * @param pys the value for yw_lib_zi.pys
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    public void setPys(String pys) {
        this.pys = pys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_lib_zi.bishun
     *
     * @return the value of yw_lib_zi.bishun
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    public String getBishun() {
        return bishun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_lib_zi.bishun
     *
     * @param bishun the value for yw_lib_zi.bishun
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    public void setBishun(String bishun) {
        this.bishun = bishun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_lib_zi.bushoupic
     *
     * @return the value of yw_lib_zi.bushoupic
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    public String getBushoupic() {
        return bushoupic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_lib_zi.bushoupic
     *
     * @param bushoupic the value for yw_lib_zi.bushoupic
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    public void setBushoupic(String bushoupic) {
        this.bushoupic = bushoupic;
    }


    @Override
    public String toString() {
        return "Zi{" +
                "id=" + id +
                ", zi='" + zi + '\'' +
                ", fzi='" + fzi + '\'' +
                ", py='" + py + '\'' +
                ", zipin=" + zipin +
                ", pinyin='" + pinyin + '\'' +
                ", wubi='" + wubi + '\'' +
                ", bushou='" + bushou + '\'' +
                ", jiegou=" + jiegou +
                ", zongbihua=" + zongbihua +
                ", buwaibihua=" + buwaibihua +
                ", pys='" + pys + '\'' +
                ", bishun='" + bishun + '\'' +
                ", bushoupic='" + bushoupic + '\'' +
                '}';
    }
}