package com.boz.bean;

import java.util.ArrayList;
import java.util.List;

public class ZiExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yw_lib_zi
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yw_lib_zi
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yw_lib_zi
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_lib_zi
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    public ZiExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_lib_zi
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_lib_zi
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_lib_zi
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_lib_zi
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_lib_zi
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_lib_zi
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_lib_zi
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_lib_zi
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_lib_zi
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_lib_zi
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yw_lib_zi
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andZiIsNull() {
            addCriterion("zi is null");
            return (Criteria) this;
        }

        public Criteria andZiIsNotNull() {
            addCriterion("zi is not null");
            return (Criteria) this;
        }

        public Criteria andZiEqualTo(String value) {
            addCriterion("zi =", value, "zi");
            return (Criteria) this;
        }

        public Criteria andZiNotEqualTo(String value) {
            addCriterion("zi <>", value, "zi");
            return (Criteria) this;
        }

        public Criteria andZiGreaterThan(String value) {
            addCriterion("zi >", value, "zi");
            return (Criteria) this;
        }

        public Criteria andZiGreaterThanOrEqualTo(String value) {
            addCriterion("zi >=", value, "zi");
            return (Criteria) this;
        }

        public Criteria andZiLessThan(String value) {
            addCriterion("zi <", value, "zi");
            return (Criteria) this;
        }

        public Criteria andZiLessThanOrEqualTo(String value) {
            addCriterion("zi <=", value, "zi");
            return (Criteria) this;
        }

        public Criteria andZiLike(String value) {
            addCriterion("zi like", value, "zi");
            return (Criteria) this;
        }

        public Criteria andZiNotLike(String value) {
            addCriterion("zi not like", value, "zi");
            return (Criteria) this;
        }

        public Criteria andZiIn(List<String> values) {
            addCriterion("zi in", values, "zi");
            return (Criteria) this;
        }

        public Criteria andZiNotIn(List<String> values) {
            addCriterion("zi not in", values, "zi");
            return (Criteria) this;
        }

        public Criteria andZiBetween(String value1, String value2) {
            addCriterion("zi between", value1, value2, "zi");
            return (Criteria) this;
        }

        public Criteria andZiNotBetween(String value1, String value2) {
            addCriterion("zi not between", value1, value2, "zi");
            return (Criteria) this;
        }

        public Criteria andFziIsNull() {
            addCriterion("fzi is null");
            return (Criteria) this;
        }

        public Criteria andFziIsNotNull() {
            addCriterion("fzi is not null");
            return (Criteria) this;
        }

        public Criteria andFziEqualTo(String value) {
            addCriterion("fzi =", value, "fzi");
            return (Criteria) this;
        }

        public Criteria andFziNotEqualTo(String value) {
            addCriterion("fzi <>", value, "fzi");
            return (Criteria) this;
        }

        public Criteria andFziGreaterThan(String value) {
            addCriterion("fzi >", value, "fzi");
            return (Criteria) this;
        }

        public Criteria andFziGreaterThanOrEqualTo(String value) {
            addCriterion("fzi >=", value, "fzi");
            return (Criteria) this;
        }

        public Criteria andFziLessThan(String value) {
            addCriterion("fzi <", value, "fzi");
            return (Criteria) this;
        }

        public Criteria andFziLessThanOrEqualTo(String value) {
            addCriterion("fzi <=", value, "fzi");
            return (Criteria) this;
        }

        public Criteria andFziLike(String value) {
            addCriterion("fzi like", value, "fzi");
            return (Criteria) this;
        }

        public Criteria andFziNotLike(String value) {
            addCriterion("fzi not like", value, "fzi");
            return (Criteria) this;
        }

        public Criteria andFziIn(List<String> values) {
            addCriterion("fzi in", values, "fzi");
            return (Criteria) this;
        }

        public Criteria andFziNotIn(List<String> values) {
            addCriterion("fzi not in", values, "fzi");
            return (Criteria) this;
        }

        public Criteria andFziBetween(String value1, String value2) {
            addCriterion("fzi between", value1, value2, "fzi");
            return (Criteria) this;
        }

        public Criteria andFziNotBetween(String value1, String value2) {
            addCriterion("fzi not between", value1, value2, "fzi");
            return (Criteria) this;
        }

        public Criteria andPyIsNull() {
            addCriterion("py is null");
            return (Criteria) this;
        }

        public Criteria andPyIsNotNull() {
            addCriterion("py is not null");
            return (Criteria) this;
        }

        public Criteria andPyEqualTo(String value) {
            addCriterion("py =", value, "py");
            return (Criteria) this;
        }

        public Criteria andPyNotEqualTo(String value) {
            addCriterion("py <>", value, "py");
            return (Criteria) this;
        }

        public Criteria andPyGreaterThan(String value) {
            addCriterion("py >", value, "py");
            return (Criteria) this;
        }

        public Criteria andPyGreaterThanOrEqualTo(String value) {
            addCriterion("py >=", value, "py");
            return (Criteria) this;
        }

        public Criteria andPyLessThan(String value) {
            addCriterion("py <", value, "py");
            return (Criteria) this;
        }

        public Criteria andPyLessThanOrEqualTo(String value) {
            addCriterion("py <=", value, "py");
            return (Criteria) this;
        }

        public Criteria andPyLike(String value) {
            addCriterion("py like", value, "py");
            return (Criteria) this;
        }

        public Criteria andPyNotLike(String value) {
            addCriterion("py not like", value, "py");
            return (Criteria) this;
        }

        public Criteria andPyIn(List<String> values) {
            addCriterion("py in", values, "py");
            return (Criteria) this;
        }

        public Criteria andPyNotIn(List<String> values) {
            addCriterion("py not in", values, "py");
            return (Criteria) this;
        }

        public Criteria andPyBetween(String value1, String value2) {
            addCriterion("py between", value1, value2, "py");
            return (Criteria) this;
        }

        public Criteria andPyNotBetween(String value1, String value2) {
            addCriterion("py not between", value1, value2, "py");
            return (Criteria) this;
        }

        public Criteria andZipinIsNull() {
            addCriterion("zipin is null");
            return (Criteria) this;
        }

        public Criteria andZipinIsNotNull() {
            addCriterion("zipin is not null");
            return (Criteria) this;
        }

        public Criteria andZipinEqualTo(Integer value) {
            addCriterion("zipin =", value, "zipin");
            return (Criteria) this;
        }

        public Criteria andZipinNotEqualTo(Integer value) {
            addCriterion("zipin <>", value, "zipin");
            return (Criteria) this;
        }

        public Criteria andZipinGreaterThan(Integer value) {
            addCriterion("zipin >", value, "zipin");
            return (Criteria) this;
        }

        public Criteria andZipinGreaterThanOrEqualTo(Integer value) {
            addCriterion("zipin >=", value, "zipin");
            return (Criteria) this;
        }

        public Criteria andZipinLessThan(Integer value) {
            addCriterion("zipin <", value, "zipin");
            return (Criteria) this;
        }

        public Criteria andZipinLessThanOrEqualTo(Integer value) {
            addCriterion("zipin <=", value, "zipin");
            return (Criteria) this;
        }

        public Criteria andZipinIn(List<Integer> values) {
            addCriterion("zipin in", values, "zipin");
            return (Criteria) this;
        }

        public Criteria andZipinNotIn(List<Integer> values) {
            addCriterion("zipin not in", values, "zipin");
            return (Criteria) this;
        }

        public Criteria andZipinBetween(Integer value1, Integer value2) {
            addCriterion("zipin between", value1, value2, "zipin");
            return (Criteria) this;
        }

        public Criteria andZipinNotBetween(Integer value1, Integer value2) {
            addCriterion("zipin not between", value1, value2, "zipin");
            return (Criteria) this;
        }

        public Criteria andPinyinIsNull() {
            addCriterion("pinyin is null");
            return (Criteria) this;
        }

        public Criteria andPinyinIsNotNull() {
            addCriterion("pinyin is not null");
            return (Criteria) this;
        }

        public Criteria andPinyinEqualTo(String value) {
            addCriterion("pinyin =", value, "pinyin");
            return (Criteria) this;
        }

        public Criteria andPinyinNotEqualTo(String value) {
            addCriterion("pinyin <>", value, "pinyin");
            return (Criteria) this;
        }

        public Criteria andPinyinGreaterThan(String value) {
            addCriterion("pinyin >", value, "pinyin");
            return (Criteria) this;
        }

        public Criteria andPinyinGreaterThanOrEqualTo(String value) {
            addCriterion("pinyin >=", value, "pinyin");
            return (Criteria) this;
        }

        public Criteria andPinyinLessThan(String value) {
            addCriterion("pinyin <", value, "pinyin");
            return (Criteria) this;
        }

        public Criteria andPinyinLessThanOrEqualTo(String value) {
            addCriterion("pinyin <=", value, "pinyin");
            return (Criteria) this;
        }

        public Criteria andPinyinLike(String value) {
            addCriterion("pinyin like", value, "pinyin");
            return (Criteria) this;
        }

        public Criteria andPinyinNotLike(String value) {
            addCriterion("pinyin not like", value, "pinyin");
            return (Criteria) this;
        }

        public Criteria andPinyinIn(List<String> values) {
            addCriterion("pinyin in", values, "pinyin");
            return (Criteria) this;
        }

        public Criteria andPinyinNotIn(List<String> values) {
            addCriterion("pinyin not in", values, "pinyin");
            return (Criteria) this;
        }

        public Criteria andPinyinBetween(String value1, String value2) {
            addCriterion("pinyin between", value1, value2, "pinyin");
            return (Criteria) this;
        }

        public Criteria andPinyinNotBetween(String value1, String value2) {
            addCriterion("pinyin not between", value1, value2, "pinyin");
            return (Criteria) this;
        }

        public Criteria andWubiIsNull() {
            addCriterion("wubi is null");
            return (Criteria) this;
        }

        public Criteria andWubiIsNotNull() {
            addCriterion("wubi is not null");
            return (Criteria) this;
        }

        public Criteria andWubiEqualTo(String value) {
            addCriterion("wubi =", value, "wubi");
            return (Criteria) this;
        }

        public Criteria andWubiNotEqualTo(String value) {
            addCriterion("wubi <>", value, "wubi");
            return (Criteria) this;
        }

        public Criteria andWubiGreaterThan(String value) {
            addCriterion("wubi >", value, "wubi");
            return (Criteria) this;
        }

        public Criteria andWubiGreaterThanOrEqualTo(String value) {
            addCriterion("wubi >=", value, "wubi");
            return (Criteria) this;
        }

        public Criteria andWubiLessThan(String value) {
            addCriterion("wubi <", value, "wubi");
            return (Criteria) this;
        }

        public Criteria andWubiLessThanOrEqualTo(String value) {
            addCriterion("wubi <=", value, "wubi");
            return (Criteria) this;
        }

        public Criteria andWubiLike(String value) {
            addCriterion("wubi like", value, "wubi");
            return (Criteria) this;
        }

        public Criteria andWubiNotLike(String value) {
            addCriterion("wubi not like", value, "wubi");
            return (Criteria) this;
        }

        public Criteria andWubiIn(List<String> values) {
            addCriterion("wubi in", values, "wubi");
            return (Criteria) this;
        }

        public Criteria andWubiNotIn(List<String> values) {
            addCriterion("wubi not in", values, "wubi");
            return (Criteria) this;
        }

        public Criteria andWubiBetween(String value1, String value2) {
            addCriterion("wubi between", value1, value2, "wubi");
            return (Criteria) this;
        }

        public Criteria andWubiNotBetween(String value1, String value2) {
            addCriterion("wubi not between", value1, value2, "wubi");
            return (Criteria) this;
        }

        public Criteria andBushouIsNull() {
            addCriterion("bushou is null");
            return (Criteria) this;
        }

        public Criteria andBushouIsNotNull() {
            addCriterion("bushou is not null");
            return (Criteria) this;
        }

        public Criteria andBushouEqualTo(String value) {
            addCriterion("bushou =", value, "bushou");
            return (Criteria) this;
        }

        public Criteria andBushouNotEqualTo(String value) {
            addCriterion("bushou <>", value, "bushou");
            return (Criteria) this;
        }

        public Criteria andBushouGreaterThan(String value) {
            addCriterion("bushou >", value, "bushou");
            return (Criteria) this;
        }

        public Criteria andBushouGreaterThanOrEqualTo(String value) {
            addCriterion("bushou >=", value, "bushou");
            return (Criteria) this;
        }

        public Criteria andBushouLessThan(String value) {
            addCriterion("bushou <", value, "bushou");
            return (Criteria) this;
        }

        public Criteria andBushouLessThanOrEqualTo(String value) {
            addCriterion("bushou <=", value, "bushou");
            return (Criteria) this;
        }

        public Criteria andBushouLike(String value) {
            addCriterion("bushou like", value, "bushou");
            return (Criteria) this;
        }

        public Criteria andBushouNotLike(String value) {
            addCriterion("bushou not like", value, "bushou");
            return (Criteria) this;
        }

        public Criteria andBushouIn(List<String> values) {
            addCriterion("bushou in", values, "bushou");
            return (Criteria) this;
        }

        public Criteria andBushouNotIn(List<String> values) {
            addCriterion("bushou not in", values, "bushou");
            return (Criteria) this;
        }

        public Criteria andBushouBetween(String value1, String value2) {
            addCriterion("bushou between", value1, value2, "bushou");
            return (Criteria) this;
        }

        public Criteria andBushouNotBetween(String value1, String value2) {
            addCriterion("bushou not between", value1, value2, "bushou");
            return (Criteria) this;
        }

        public Criteria andJiegouIsNull() {
            addCriterion("jiegou is null");
            return (Criteria) this;
        }

        public Criteria andJiegouIsNotNull() {
            addCriterion("jiegou is not null");
            return (Criteria) this;
        }

        public Criteria andJiegouEqualTo(Integer value) {
            addCriterion("jiegou =", value, "jiegou");
            return (Criteria) this;
        }

        public Criteria andJiegouNotEqualTo(Integer value) {
            addCriterion("jiegou <>", value, "jiegou");
            return (Criteria) this;
        }

        public Criteria andJiegouGreaterThan(Integer value) {
            addCriterion("jiegou >", value, "jiegou");
            return (Criteria) this;
        }

        public Criteria andJiegouGreaterThanOrEqualTo(Integer value) {
            addCriterion("jiegou >=", value, "jiegou");
            return (Criteria) this;
        }

        public Criteria andJiegouLessThan(Integer value) {
            addCriterion("jiegou <", value, "jiegou");
            return (Criteria) this;
        }

        public Criteria andJiegouLessThanOrEqualTo(Integer value) {
            addCriterion("jiegou <=", value, "jiegou");
            return (Criteria) this;
        }

        public Criteria andJiegouIn(List<Integer> values) {
            addCriterion("jiegou in", values, "jiegou");
            return (Criteria) this;
        }

        public Criteria andJiegouNotIn(List<Integer> values) {
            addCriterion("jiegou not in", values, "jiegou");
            return (Criteria) this;
        }

        public Criteria andJiegouBetween(Integer value1, Integer value2) {
            addCriterion("jiegou between", value1, value2, "jiegou");
            return (Criteria) this;
        }

        public Criteria andJiegouNotBetween(Integer value1, Integer value2) {
            addCriterion("jiegou not between", value1, value2, "jiegou");
            return (Criteria) this;
        }

        public Criteria andZongbihuaIsNull() {
            addCriterion("zongbihua is null");
            return (Criteria) this;
        }

        public Criteria andZongbihuaIsNotNull() {
            addCriterion("zongbihua is not null");
            return (Criteria) this;
        }

        public Criteria andZongbihuaEqualTo(Integer value) {
            addCriterion("zongbihua =", value, "zongbihua");
            return (Criteria) this;
        }

        public Criteria andZongbihuaNotEqualTo(Integer value) {
            addCriterion("zongbihua <>", value, "zongbihua");
            return (Criteria) this;
        }

        public Criteria andZongbihuaGreaterThan(Integer value) {
            addCriterion("zongbihua >", value, "zongbihua");
            return (Criteria) this;
        }

        public Criteria andZongbihuaGreaterThanOrEqualTo(Integer value) {
            addCriterion("zongbihua >=", value, "zongbihua");
            return (Criteria) this;
        }

        public Criteria andZongbihuaLessThan(Integer value) {
            addCriterion("zongbihua <", value, "zongbihua");
            return (Criteria) this;
        }

        public Criteria andZongbihuaLessThanOrEqualTo(Integer value) {
            addCriterion("zongbihua <=", value, "zongbihua");
            return (Criteria) this;
        }

        public Criteria andZongbihuaIn(List<Integer> values) {
            addCriterion("zongbihua in", values, "zongbihua");
            return (Criteria) this;
        }

        public Criteria andZongbihuaNotIn(List<Integer> values) {
            addCriterion("zongbihua not in", values, "zongbihua");
            return (Criteria) this;
        }

        public Criteria andZongbihuaBetween(Integer value1, Integer value2) {
            addCriterion("zongbihua between", value1, value2, "zongbihua");
            return (Criteria) this;
        }

        public Criteria andZongbihuaNotBetween(Integer value1, Integer value2) {
            addCriterion("zongbihua not between", value1, value2, "zongbihua");
            return (Criteria) this;
        }

        public Criteria andBuwaibihuaIsNull() {
            addCriterion("buwaibihua is null");
            return (Criteria) this;
        }

        public Criteria andBuwaibihuaIsNotNull() {
            addCriterion("buwaibihua is not null");
            return (Criteria) this;
        }

        public Criteria andBuwaibihuaEqualTo(Integer value) {
            addCriterion("buwaibihua =", value, "buwaibihua");
            return (Criteria) this;
        }

        public Criteria andBuwaibihuaNotEqualTo(Integer value) {
            addCriterion("buwaibihua <>", value, "buwaibihua");
            return (Criteria) this;
        }

        public Criteria andBuwaibihuaGreaterThan(Integer value) {
            addCriterion("buwaibihua >", value, "buwaibihua");
            return (Criteria) this;
        }

        public Criteria andBuwaibihuaGreaterThanOrEqualTo(Integer value) {
            addCriterion("buwaibihua >=", value, "buwaibihua");
            return (Criteria) this;
        }

        public Criteria andBuwaibihuaLessThan(Integer value) {
            addCriterion("buwaibihua <", value, "buwaibihua");
            return (Criteria) this;
        }

        public Criteria andBuwaibihuaLessThanOrEqualTo(Integer value) {
            addCriterion("buwaibihua <=", value, "buwaibihua");
            return (Criteria) this;
        }

        public Criteria andBuwaibihuaIn(List<Integer> values) {
            addCriterion("buwaibihua in", values, "buwaibihua");
            return (Criteria) this;
        }

        public Criteria andBuwaibihuaNotIn(List<Integer> values) {
            addCriterion("buwaibihua not in", values, "buwaibihua");
            return (Criteria) this;
        }

        public Criteria andBuwaibihuaBetween(Integer value1, Integer value2) {
            addCriterion("buwaibihua between", value1, value2, "buwaibihua");
            return (Criteria) this;
        }

        public Criteria andBuwaibihuaNotBetween(Integer value1, Integer value2) {
            addCriterion("buwaibihua not between", value1, value2, "buwaibihua");
            return (Criteria) this;
        }

        public Criteria andPysIsNull() {
            addCriterion("pys is null");
            return (Criteria) this;
        }

        public Criteria andPysIsNotNull() {
            addCriterion("pys is not null");
            return (Criteria) this;
        }

        public Criteria andPysEqualTo(String value) {
            addCriterion("pys =", value, "pys");
            return (Criteria) this;
        }

        public Criteria andPysNotEqualTo(String value) {
            addCriterion("pys <>", value, "pys");
            return (Criteria) this;
        }

        public Criteria andPysGreaterThan(String value) {
            addCriterion("pys >", value, "pys");
            return (Criteria) this;
        }

        public Criteria andPysGreaterThanOrEqualTo(String value) {
            addCriterion("pys >=", value, "pys");
            return (Criteria) this;
        }

        public Criteria andPysLessThan(String value) {
            addCriterion("pys <", value, "pys");
            return (Criteria) this;
        }

        public Criteria andPysLessThanOrEqualTo(String value) {
            addCriterion("pys <=", value, "pys");
            return (Criteria) this;
        }

        public Criteria andPysLike(String value) {
            addCriterion("pys like", value, "pys");
            return (Criteria) this;
        }

        public Criteria andPysNotLike(String value) {
            addCriterion("pys not like", value, "pys");
            return (Criteria) this;
        }

        public Criteria andPysIn(List<String> values) {
            addCriterion("pys in", values, "pys");
            return (Criteria) this;
        }

        public Criteria andPysNotIn(List<String> values) {
            addCriterion("pys not in", values, "pys");
            return (Criteria) this;
        }

        public Criteria andPysBetween(String value1, String value2) {
            addCriterion("pys between", value1, value2, "pys");
            return (Criteria) this;
        }

        public Criteria andPysNotBetween(String value1, String value2) {
            addCriterion("pys not between", value1, value2, "pys");
            return (Criteria) this;
        }

        public Criteria andBishunIsNull() {
            addCriterion("bishun is null");
            return (Criteria) this;
        }

        public Criteria andBishunIsNotNull() {
            addCriterion("bishun is not null");
            return (Criteria) this;
        }

        public Criteria andBishunEqualTo(String value) {
            addCriterion("bishun =", value, "bishun");
            return (Criteria) this;
        }

        public Criteria andBishunNotEqualTo(String value) {
            addCriterion("bishun <>", value, "bishun");
            return (Criteria) this;
        }

        public Criteria andBishunGreaterThan(String value) {
            addCriterion("bishun >", value, "bishun");
            return (Criteria) this;
        }

        public Criteria andBishunGreaterThanOrEqualTo(String value) {
            addCriterion("bishun >=", value, "bishun");
            return (Criteria) this;
        }

        public Criteria andBishunLessThan(String value) {
            addCriterion("bishun <", value, "bishun");
            return (Criteria) this;
        }

        public Criteria andBishunLessThanOrEqualTo(String value) {
            addCriterion("bishun <=", value, "bishun");
            return (Criteria) this;
        }

        public Criteria andBishunLike(String value) {
            addCriterion("bishun like", value, "bishun");
            return (Criteria) this;
        }

        public Criteria andBishunNotLike(String value) {
            addCriterion("bishun not like", value, "bishun");
            return (Criteria) this;
        }

        public Criteria andBishunIn(List<String> values) {
            addCriterion("bishun in", values, "bishun");
            return (Criteria) this;
        }

        public Criteria andBishunNotIn(List<String> values) {
            addCriterion("bishun not in", values, "bishun");
            return (Criteria) this;
        }

        public Criteria andBishunBetween(String value1, String value2) {
            addCriterion("bishun between", value1, value2, "bishun");
            return (Criteria) this;
        }

        public Criteria andBishunNotBetween(String value1, String value2) {
            addCriterion("bishun not between", value1, value2, "bishun");
            return (Criteria) this;
        }

        public Criteria andBushoupicIsNull() {
            addCriterion("bushoupic is null");
            return (Criteria) this;
        }

        public Criteria andBushoupicIsNotNull() {
            addCriterion("bushoupic is not null");
            return (Criteria) this;
        }

        public Criteria andBushoupicEqualTo(String value) {
            addCriterion("bushoupic =", value, "bushoupic");
            return (Criteria) this;
        }

        public Criteria andBushoupicNotEqualTo(String value) {
            addCriterion("bushoupic <>", value, "bushoupic");
            return (Criteria) this;
        }

        public Criteria andBushoupicGreaterThan(String value) {
            addCriterion("bushoupic >", value, "bushoupic");
            return (Criteria) this;
        }

        public Criteria andBushoupicGreaterThanOrEqualTo(String value) {
            addCriterion("bushoupic >=", value, "bushoupic");
            return (Criteria) this;
        }

        public Criteria andBushoupicLessThan(String value) {
            addCriterion("bushoupic <", value, "bushoupic");
            return (Criteria) this;
        }

        public Criteria andBushoupicLessThanOrEqualTo(String value) {
            addCriterion("bushoupic <=", value, "bushoupic");
            return (Criteria) this;
        }

        public Criteria andBushoupicLike(String value) {
            addCriterion("bushoupic like", value, "bushoupic");
            return (Criteria) this;
        }

        public Criteria andBushoupicNotLike(String value) {
            addCriterion("bushoupic not like", value, "bushoupic");
            return (Criteria) this;
        }

        public Criteria andBushoupicIn(List<String> values) {
            addCriterion("bushoupic in", values, "bushoupic");
            return (Criteria) this;
        }

        public Criteria andBushoupicNotIn(List<String> values) {
            addCriterion("bushoupic not in", values, "bushoupic");
            return (Criteria) this;
        }

        public Criteria andBushoupicBetween(String value1, String value2) {
            addCriterion("bushoupic between", value1, value2, "bushoupic");
            return (Criteria) this;
        }

        public Criteria andBushoupicNotBetween(String value1, String value2) {
            addCriterion("bushoupic not between", value1, value2, "bushoupic");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yw_lib_zi
     *
     * @mbg.generated do_not_delete_during_merge Fri Mar 08 13:20:11 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yw_lib_zi
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}