package com.boz.mapper;

import com.boz.bean.Cixing;
import com.boz.bean.CixingExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Service;

import java.util.List;

@Mapper
@Service
public interface CixingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_lib_cixing
     *
     * @mbg.generated Fri Mar 08 13:29:48 CST 2019
     */
    long countByExample(CixingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_lib_cixing
     *
     * @mbg.generated Fri Mar 08 13:29:48 CST 2019
     */
    int deleteByExample(CixingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_lib_cixing
     *
     * @mbg.generated Fri Mar 08 13:29:48 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_lib_cixing
     *
     * @mbg.generated Fri Mar 08 13:29:48 CST 2019
     */
    int insert(Cixing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_lib_cixing
     *
     * @mbg.generated Fri Mar 08 13:29:48 CST 2019
     */
    int insertSelective(Cixing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_lib_cixing
     *
     * @mbg.generated Fri Mar 08 13:29:48 CST 2019
     */
    List<Cixing> selectByExample(CixingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_lib_cixing
     *
     * @mbg.generated Fri Mar 08 13:29:48 CST 2019
     */
    Cixing selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_lib_cixing
     *
     * @mbg.generated Fri Mar 08 13:29:48 CST 2019
     */
    int updateByExampleSelective(@Param("record") Cixing record, @Param("example") CixingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_lib_cixing
     *
     * @mbg.generated Fri Mar 08 13:29:48 CST 2019
     */
    int updateByExample(@Param("record") Cixing record, @Param("example") CixingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_lib_cixing
     *
     * @mbg.generated Fri Mar 08 13:29:48 CST 2019
     */
    int updateByPrimaryKeySelective(Cixing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_lib_cixing
     *
     * @mbg.generated Fri Mar 08 13:29:48 CST 2019
     */
    int updateByPrimaryKey(Cixing record);
}