package com.boz.mapper;

import com.boz.bean.MusicGroup;
import com.boz.bean.MusicGroupExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
@Mapper
public interface MusicGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_music_group
     *
     * @mbg.generated Wed Jan 23 12:52:54 CST 2019
     */
    long countByExample(MusicGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_music_group
     *
     * @mbg.generated Wed Jan 23 12:52:54 CST 2019
     */
    int deleteByExample(MusicGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_music_group
     *
     * @mbg.generated Wed Jan 23 12:52:54 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_music_group
     *
     * @mbg.generated Wed Jan 23 12:52:54 CST 2019
     */
    int insert(MusicGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_music_group
     *
     * @mbg.generated Wed Jan 23 12:52:54 CST 2019
     */
    int insertSelective(MusicGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_music_group
     *
     * @mbg.generated Wed Jan 23 12:52:54 CST 2019
     */
    List<MusicGroup> selectByExample(MusicGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_music_group
     *
     * @mbg.generated Wed Jan 23 12:52:54 CST 2019
     */
    MusicGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_music_group
     *
     * @mbg.generated Wed Jan 23 12:52:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") MusicGroup record, @Param("example") MusicGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_music_group
     *
     * @mbg.generated Wed Jan 23 12:52:54 CST 2019
     */
    int updateByExample(@Param("record") MusicGroup record, @Param("example") MusicGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_music_group
     *
     * @mbg.generated Wed Jan 23 12:52:54 CST 2019
     */
    int updateByPrimaryKeySelective(MusicGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_music_group
     *
     * @mbg.generated Wed Jan 23 12:52:54 CST 2019
     */
    int updateByPrimaryKey(MusicGroup record);
}