package com.boz.mapper;

import com.boz.bean.MusicInfo;
import com.boz.bean.MusicInfoExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Map;

@Mapper
@Service
public interface MusicInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_music_info
     *
     * @mbg.generated Wed Jan 23 12:52:39 CST 2019
     */
    long countByExample(MusicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_music_info
     *
     * @mbg.generated Wed Jan 23 12:52:39 CST 2019
     */
    int deleteByExample(MusicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_music_info
     *
     * @mbg.generated Wed Jan 23 12:52:39 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_music_info
     *
     * @mbg.generated Wed Jan 23 12:52:39 CST 2019
     */
    int insert(MusicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_music_info
     *
     * @mbg.generated Wed Jan 23 12:52:39 CST 2019
     */
    int insertSelective(MusicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_music_info
     *
     * @mbg.generated Wed Jan 23 12:52:39 CST 2019
     */
    List<MusicInfo> selectByExample(MusicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_music_info
     *
     * @mbg.generated Wed Jan 23 12:52:39 CST 2019
     */
    MusicInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_music_info
     *
     * @mbg.generated Wed Jan 23 12:52:39 CST 2019
     */
    int updateByExampleSelective(@Param("record") MusicInfo record, @Param("example") MusicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_music_info
     *
     * @mbg.generated Wed Jan 23 12:52:39 CST 2019
     */
    int updateByExample(@Param("record") MusicInfo record, @Param("example") MusicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_music_info
     *
     * @mbg.generated Wed Jan 23 12:52:39 CST 2019
     */
    int updateByPrimaryKeySelective(MusicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_music_info
     *
     * @mbg.generated Wed Jan 23 12:52:39 CST 2019
     */
    int updateByPrimaryKey(MusicInfo record);


    List<MusicInfo> selectByPage(Map<String, Object> map);
}