package com.boz.mapper;

import com.boz.bean.UserAdmin;
import com.boz.bean.UserAdminExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Map;

@Mapper
@Service
public interface UserAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_user_admin
     *
     * @mbg.generated Tue Jan 22 11:25:52 CST 2019
     */
    long countByExample(UserAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_user_admin
     *
     * @mbg.generated Tue Jan 22 11:25:52 CST 2019
     */
    int deleteByExample(UserAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_user_admin
     *
     * @mbg.generated Tue Jan 22 11:25:52 CST 2019
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_user_admin
     *
     * @mbg.generated Tue Jan 22 11:25:52 CST 2019
     */
    int insert(UserAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_user_admin
     *
     * @mbg.generated Tue Jan 22 11:25:52 CST 2019
     */
    int insertSelective(UserAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_user_admin
     *
     * @mbg.generated Tue Jan 22 11:25:52 CST 2019
     */
    List<UserAdmin> selectByExample(UserAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_user_admin
     *
     * @mbg.generated Tue Jan 22 11:25:52 CST 2019
     */
    UserAdmin selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_user_admin
     *
     * @mbg.generated Tue Jan 22 11:25:52 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserAdmin record, @Param("example") UserAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_user_admin
     *
     * @mbg.generated Tue Jan 22 11:25:52 CST 2019
     */
    int updateByExample(@Param("record") UserAdmin record, @Param("example") UserAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_user_admin
     *
     * @mbg.generated Tue Jan 22 11:25:52 CST 2019
     */
    int updateByPrimaryKeySelective(UserAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_user_admin
     *
     * @mbg.generated Tue Jan 22 11:25:52 CST 2019
     */
    int updateByPrimaryKey(UserAdmin record);

    List<UserAdmin> selectByPage(Map<String, Object> map);
}