package com.boz.mapper;

import com.boz.bean.Zi;
import com.boz.bean.ZiExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Service;

import java.util.List;

@Mapper
@Service
public interface ZiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_lib_zi
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    long countByExample(ZiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_lib_zi
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    int deleteByExample(ZiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_lib_zi
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_lib_zi
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    int insert(Zi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_lib_zi
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    int insertSelective(Zi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_lib_zi
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    List<Zi> selectByExample(ZiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_lib_zi
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    Zi selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_lib_zi
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    int updateByExampleSelective(@Param("record") Zi record, @Param("example") ZiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_lib_zi
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    int updateByExample(@Param("record") Zi record, @Param("example") ZiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_lib_zi
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    int updateByPrimaryKeySelective(Zi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_lib_zi
     *
     * @mbg.generated Fri Mar 08 13:20:11 CST 2019
     */
    int updateByPrimaryKey(Zi record);
}